package generator

import (
	"strings"
	"text/template"
)

// templates maps resource types to their HCL templates.
var templates = map[string]*template.Template{}

func init() {
	// Register all templates
	registerTemplate("variable", variableTemplate)
	registerTemplate("script", scriptTemplate)
	registerTemplate("credential", credentialTemplate)
	registerTemplate("business_service", businessServiceTemplate)
	registerTemplate("calendar", calendarTemplate)
	registerTemplate("agent_cluster", agentClusterTemplate)
	registerTemplate("database_connection", databaseConnectionTemplate)
	registerTemplate("email_connection", emailConnectionTemplate)
	registerTemplate("task_unix", taskUnixTemplate)
	registerTemplate("task_windows", taskWindowsTemplate)
	registerTemplate("task_sql", taskSQLTemplate)
	registerTemplate("task_email", taskEmailTemplate)
	registerTemplate("task_workflow", taskWorkflowTemplate)
	registerTemplate("task_file_monitor", taskFileMonitorTemplate)
	registerTemplate("task_file_transfer", taskFileTransferTemplate)
	registerTemplate("task_timer", taskTimerTemplate)
	registerTemplate("task_monitor", taskMonitorTemplate)
	registerTemplate("task_stored_procedure", taskStoredProcedureTemplate)
	registerTemplate("task_web_service", taskWebServiceTemplate)
	registerTemplate("task_universal_aws_s3", taskUniversalAWSS3Template)
	registerTemplate("trigger_time", triggerTimeTemplate)
	registerTemplate("trigger_cron", triggerCronTemplate)
	registerTemplate("trigger_file_monitor", triggerFileMonitorTemplate)
	registerTemplate("trigger_task_monitor", triggerTaskMonitorTemplate)
	registerTemplate("workflow_vertex", workflowVertexTemplate)
	registerTemplate("workflow_edge", workflowEdgeTemplate)

	// Set the GetTemplate function in generator.go
	GetTemplate = func(resourceType string) *template.Template {
		return templates[resourceType]
	}
}

func registerTemplate(name, tmpl string) {
	t := template.New(name).Funcs(template.FuncMap{
		"quote":      quote,
		"stringList": stringList,
		"notEmpty":   notEmpty,
		"isTrue":     isTrue,
	})
	templates[name] = template.Must(t.Parse(tmpl))
}

// Template helper functions
func quote(s interface{}) string {
	if s == nil {
		return ""
	}
	str, ok := s.(string)
	if !ok {
		return ""
	}
	// Escape backslashes and quotes
	str = strings.ReplaceAll(str, "\\", "\\\\")
	str = strings.ReplaceAll(str, "\"", "\\\"")
	// Escape $ to $$ for Terraform (prevents interpolation)
	str = strings.ReplaceAll(str, "$", "$$")
	return str
}

func stringList(v interface{}) string {
	if v == nil {
		return ""
	}
	list, ok := v.([]interface{})
	if !ok {
		return ""
	}
	var parts []string
	for _, item := range list {
		if s, ok := item.(string); ok {
			parts = append(parts, "\""+quote(s)+"\"")
		}
	}
	return strings.Join(parts, ", ")
}

func notEmpty(v interface{}) bool {
	if v == nil {
		return false
	}
	switch val := v.(type) {
	case string:
		return val != ""
	case []interface{}:
		return len(val) > 0
	case bool:
		return true // booleans are always "not empty" for template purposes
	default:
		return false
	}
}

func isTrue(v interface{}) bool {
	if v == nil {
		return false
	}
	b, ok := v.(bool)
	return ok && b
}

// ============================================================================
// Simple Resources
// ============================================================================

const variableTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .value}}
  value = "{{quote .value}}"
{{- end}}
{{- if notEmpty .description}}
  description = "{{quote .description}}"
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

const scriptTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .scriptType}}
  script_type = "{{quote .scriptType}}"
{{- end}}
{{- if notEmpty .content}}
  content = <<-EOT
{{.content}}
EOT
{{- end}}
{{- if notEmpty .description}}
  description = "{{quote .description}}"
{{- end}}
{{- if isTrue .resolveVariables}}
  resolve_variables = true
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

const credentialTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .runtimeUser}}
  runtime_user = "{{quote .runtimeUser}}"
{{- end}}
  # Note: password/key_location cannot be exported for security reasons
{{- if notEmpty .description}}
  description = "{{quote .description}}"
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

const businessServiceTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .description}}
  description = "{{quote .description}}"
{{- end}}
}
`

const calendarTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .comments}}
  comments = "{{quote .comments}}"
{{- end}}
{{- if notEmpty .businessDays}}
  business_days = "{{quote .businessDays}}"
{{- end}}
{{- if notEmpty .firstDayOfWeek}}
  first_day_of_week = "{{quote .firstDayOfWeek}}"
{{- end}}
{{- if notEmpty .firstQuarterMonth}}
  first_quarter_month = "{{quote .firstQuarterMonth}}"
  first_quarter_day = {{.firstQuarterDay}}
{{- end}}
{{- if notEmpty .secondQuarterMonth}}
  second_quarter_month = "{{quote .secondQuarterMonth}}"
  second_quarter_day = {{.secondQuarterDay}}
{{- end}}
{{- if notEmpty .thirdQuarterMonth}}
  third_quarter_month = "{{quote .thirdQuarterMonth}}"
  third_quarter_day = {{.thirdQuarterDay}}
{{- end}}
{{- if notEmpty .fourthQuarterMonth}}
  fourth_quarter_month = "{{quote .fourthQuarterMonth}}"
  fourth_quarter_day = {{.fourthQuarterDay}}
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

const agentClusterTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .type}}
  type = "{{quote .type}}"
{{- end}}
{{- if notEmpty .description}}
  description = "{{quote .description}}"
{{- end}}
{{- if notEmpty .distribution}}
  distribution = "{{quote .distribution}}"
{{- end}}
{{- if notEmpty .limitType}}
  limit_type = "{{quote .limitType}}"
{{- end}}
{{- if notEmpty .limitAmount}}
  limit_amount = {{.limitAmount}}
{{- end}}
{{- if notEmpty .agents}}
  agents = [{{stringList .agents}}]
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

// ============================================================================
// Connections
// ============================================================================

const databaseConnectionTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .dbDriver}}
  db_driver = "{{quote .dbDriver}}"
{{- end}}
{{- if notEmpty .dbUrl}}
  db_url = "{{quote .dbUrl}}"
{{- end}}
{{- if notEmpty .credentials}}
  credentials = "{{quote .credentials}}"
{{- end}}
{{- if notEmpty .credentialsVar}}
  credentials_var = "{{quote .credentialsVar}}"
{{- end}}
{{- if notEmpty .description}}
  description = "{{quote .description}}"
{{- end}}
{{- if notEmpty .maxRows}}
  max_rows = {{.maxRows}}
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

const emailConnectionTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .smtp}}
  smtp = "{{quote .smtp}}"
{{- end}}
{{- if notEmpty .smtpPort}}
  smtp_port = {{.smtpPort}}
{{- end}}
{{- if isTrue .smtpSsl}}
  smtp_ssl = true
{{- end}}
{{- if isTrue .smtpStarttls}}
  smtp_starttls = true
{{- end}}
{{- if notEmpty .emailAddress}}
  email_address = "{{quote .emailAddress}}"
{{- end}}
{{- if notEmpty .authentication}}
  authentication = "{{quote .authentication}}"
{{- end}}
{{- if notEmpty .authenticationType}}
  authentication_type = "{{quote .authenticationType}}"
{{- end}}
{{- if notEmpty .defaultUser}}
  default_user = "{{quote .defaultUser}}"
{{- end}}
  # Note: default_password cannot be exported for security reasons
{{- if notEmpty .description}}
  description = "{{quote .description}}"
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

// ============================================================================
// Task Resources
// ============================================================================

const taskUnixTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .summary}}
  summary = "{{quote .summary}}"
{{- end}}
{{- if notEmpty .agent}}
  agent = "{{quote .agent}}"
{{- end}}
{{- if notEmpty .agentCluster}}
  agent_cluster = "{{quote .agentCluster}}"
{{- end}}
{{- if notEmpty .agentVar}}
  agent_var = "{{quote .agentVar}}"
{{- end}}
{{- if notEmpty .agentClusterVar}}
  agent_cluster_var = "{{quote .agentClusterVar}}"
{{- end}}
{{- if notEmpty .command}}
  command = "{{quote .command}}"
{{- end}}
{{- if notEmpty .commandOrScript}}
  command_or_script = "{{quote .commandOrScript}}"
{{- end}}
{{- if notEmpty .script}}
  script = "{{quote .script}}"
{{- end}}
{{- if notEmpty .runtimeDir}}
  runtime_dir = "{{quote .runtimeDir}}"
{{- end}}
{{- if notEmpty .parameters}}
  parameters = "{{quote .parameters}}"
{{- end}}
{{- if notEmpty .credentials}}
  credentials = "{{quote .credentials}}"
{{- end}}
{{- if notEmpty .credentialsVar}}
  credentials_var = "{{quote .credentialsVar}}"
{{- end}}
{{- if notEmpty .exitCodes}}
  exit_codes = "{{quote .exitCodes}}"
{{- end}}
{{- if notEmpty .exitCodeProcessing}}
  exit_code_processing = "{{quote .exitCodeProcessing}}"
{{- end}}
{{- if isTrue .runAsSudo}}
  run_as_sudo = true
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

const taskWindowsTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .summary}}
  summary = "{{quote .summary}}"
{{- end}}
{{- if notEmpty .agent}}
  agent = "{{quote .agent}}"
{{- end}}
{{- if notEmpty .agentCluster}}
  agent_cluster = "{{quote .agentCluster}}"
{{- end}}
{{- if notEmpty .agentVar}}
  agent_var = "{{quote .agentVar}}"
{{- end}}
{{- if notEmpty .agentClusterVar}}
  agent_cluster_var = "{{quote .agentClusterVar}}"
{{- end}}
{{- if notEmpty .command}}
  command = "{{quote .command}}"
{{- end}}
{{- if notEmpty .commandOrScript}}
  command_or_script = "{{quote .commandOrScript}}"
{{- end}}
{{- if notEmpty .script}}
  script = "{{quote .script}}"
{{- end}}
{{- if notEmpty .runtimeDir}}
  runtime_dir = "{{quote .runtimeDir}}"
{{- end}}
{{- if notEmpty .parameters}}
  parameters = "{{quote .parameters}}"
{{- end}}
{{- if notEmpty .credentials}}
  credentials = "{{quote .credentials}}"
{{- end}}
{{- if notEmpty .credentialsVar}}
  credentials_var = "{{quote .credentialsVar}}"
{{- end}}
{{- if notEmpty .exitCodes}}
  exit_codes = "{{quote .exitCodes}}"
{{- end}}
{{- if notEmpty .exitCodeProcessing}}
  exit_code_processing = "{{quote .exitCodeProcessing}}"
{{- end}}
{{- if isTrue .elevateUser}}
  elevate_user = true
{{- end}}
{{- if isTrue .desktopInteract}}
  desktop_interact = true
{{- end}}
{{- if isTrue .createConsole}}
  create_console = true
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

const taskSQLTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .summary}}
  summary = "{{quote .summary}}"
{{- end}}
{{- if notEmpty .databaseConnection}}
  database_connection = "{{quote .databaseConnection}}"
{{- end}}
{{- if notEmpty .sqlStatement}}
  sql_statement = "{{quote .sqlStatement}}"
{{- end}}
{{- if notEmpty .sqlCommand}}
  sql_command = "{{quote .sqlCommand}}"
{{- end}}
{{- if notEmpty .columnType}}
  column_type = "{{quote .columnType}}"
{{- end}}
{{- if notEmpty .columnValue}}
  column_value = "{{quote .columnValue}}"
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

const taskEmailTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .summary}}
  summary = "{{quote .summary}}"
{{- end}}
{{- if notEmpty .emailConnection}}
  email_connection = "{{quote .emailConnection}}"
{{- end}}
{{- if notEmpty .emailConnectionVar}}
  email_connection_var = "{{quote .emailConnectionVar}}"
{{- end}}
{{- if notEmpty .template}}
  template = "{{quote .template}}"
{{- end}}
{{- if notEmpty .toRecipients}}
  to_recipients = "{{quote .toRecipients}}"
{{- end}}
{{- if notEmpty .ccRecipients}}
  cc_recipients = "{{quote .ccRecipients}}"
{{- end}}
{{- if notEmpty .bccRecipients}}
  bcc_recipients = "{{quote .bccRecipients}}"
{{- end}}
{{- if notEmpty .replyTo}}
  reply_to = "{{quote .replyTo}}"
{{- end}}
{{- if notEmpty .subject}}
  subject = "{{quote .subject}}"
{{- end}}
{{- if notEmpty .body}}
  body = "{{quote .body}}"
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

const taskWorkflowTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .summary}}
  summary = "{{quote .summary}}"
{{- end}}
{{- if isTrue .calculateCriticalPath}}
  calculate_critical_path = true
{{- end}}
{{- if notEmpty .skippedOption}}
  skipped_option = "{{quote .skippedOption}}"
{{- end}}
{{- if notEmpty .instanceWait}}
  instance_wait = "{{quote .instanceWait}}"
{{- end}}
{{- if notEmpty .instanceWaitLookup}}
  instance_wait_lookup = "{{quote .instanceWaitLookup}}"
{{- end}}
{{- if notEmpty .layoutOption}}
  layout_option = "{{quote .layoutOption}}"
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

const taskFileMonitorTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .summary}}
  summary = "{{quote .summary}}"
{{- end}}
{{- if notEmpty .agent}}
  agent = "{{quote .agent}}"
{{- end}}
{{- if notEmpty .agentCluster}}
  agent_cluster = "{{quote .agentCluster}}"
{{- end}}
{{- if notEmpty .fileName}}
  file_name = "{{quote .fileName}}"
{{- end}}
{{- if isTrue .useRegex}}
  use_regex = true
{{- end}}
{{- if notEmpty .stableSeconds}}
  stable_seconds = {{.stableSeconds}}
{{- end}}
{{- if notEmpty .fmType}}
  fm_type = "{{quote .fmType}}"
{{- end}}
{{- if isTrue .recursive}}
  recursive = true
{{- end}}
{{- if isTrue .triggerOnExist}}
  trigger_on_exist = true
{{- end}}
{{- if isTrue .triggerOnCreate}}
  trigger_on_create = true
{{- end}}
{{- if notEmpty .credentials}}
  credentials = "{{quote .credentials}}"
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

const taskFileTransferTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .summary}}
  summary = "{{quote .summary}}"
{{- end}}
{{- if notEmpty .agent}}
  agent = "{{quote .agent}}"
{{- end}}
{{- if notEmpty .agentCluster}}
  agent_cluster = "{{quote .agentCluster}}"
{{- end}}
{{- if notEmpty .agentVar}}
  agent_var = "{{quote .agentVar}}"
{{- end}}
{{- if notEmpty .agentClusterVar}}
  agent_cluster_var = "{{quote .agentClusterVar}}"
{{- end}}
{{- if notEmpty .transferDirection}}
  transfer_direction = "{{quote .transferDirection}}"
{{- end}}
{{- if notEmpty .transferMode}}
  transfer_mode = "{{quote .transferMode}}"
{{- end}}
{{- if notEmpty .serverType}}
  server_type = "{{quote .serverType}}"
{{- end}}
{{- if notEmpty .remoteServer}}
  remote_server = "{{quote .remoteServer}}"
{{- end}}
{{- if notEmpty .remoteFilename}}
  remote_filename = "{{quote .remoteFilename}}"
{{- end}}
{{- if notEmpty .remoteCredentials}}
  remote_credentials = "{{quote .remoteCredentials}}"
{{- end}}
{{- if notEmpty .remoteCredVar}}
  remote_credentials_var = "{{quote .remoteCredVar}}"
{{- end}}
{{- if notEmpty .localFilename}}
  local_filename = "{{quote .localFilename}}"
{{- end}}
{{- if notEmpty .credentials}}
  credentials = "{{quote .credentials}}"
{{- end}}
{{- if notEmpty .credentialsVar}}
  credentials_var = "{{quote .credentialsVar}}"
{{- end}}
{{- if notEmpty .exitCodes}}
  exit_codes = "{{quote .exitCodes}}"
{{- end}}
{{- if notEmpty .exitCodeProcessing}}
  exit_code_processing = "{{quote .exitCodeProcessing}}"
{{- end}}
{{- if isTrue .useRegex}}
  use_regex = true
{{- end}}
{{- if notEmpty .encrypt}}
  encrypt = "{{quote .encrypt}}"
{{- end}}
{{- if notEmpty .compress}}
  compress = "{{quote .compress}}"
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

const taskTimerTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .summary}}
  summary = "{{quote .summary}}"
{{- end}}
{{- if notEmpty .timerType}}
  timer_type = "{{quote .timerType}}"
{{- end}}
{{- if notEmpty .timerDuration}}
  timer_duration = "{{quote .timerDuration}}"
{{- end}}
{{- if notEmpty .timerTime}}
  timer_time = "{{quote .timerTime}}"
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

const taskMonitorTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .summary}}
  summary = "{{quote .summary}}"
{{- end}}
{{- if notEmpty .taskMonName}}
  task_mon_name = "{{quote .taskMonName}}"
{{- end}}
{{- if notEmpty .statusText}}
  status_text = "{{quote .statusText}}"
{{- end}}
{{- if notEmpty .monType}}
  mon_type = "{{quote .monType}}"
{{- end}}
{{- if notEmpty .typeText}}
  type_text = "{{quote .typeText}}"
{{- end}}
{{- if notEmpty .timeScope}}
  time_scope = "{{quote .timeScope}}"
{{- end}}
{{- if isTrue .monitorLateStart}}
  monitor_late_start = true
{{- end}}
{{- if isTrue .monitorLateFinish}}
  monitor_late_finish = true
{{- end}}
{{- if isTrue .monitorEarlyFinish}}
  monitor_early_finish = true
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

const taskStoredProcedureTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .summary}}
  summary = "{{quote .summary}}"
{{- end}}
{{- if notEmpty .storedProcName}}
  stored_proc_name = "{{quote .storedProcName}}"
{{- end}}
{{- if notEmpty .databaseConnection}}
  database_connection = "{{quote .databaseConnection}}"
{{- end}}
{{- if notEmpty .connectionVar}}
  connection_var = "{{quote .connectionVar}}"
{{- end}}
{{- if notEmpty .maxRows}}
  max_rows = {{.maxRows}}
{{- end}}
{{- if isTrue .autoCleanup}}
  auto_cleanup = true
{{- end}}
{{- if notEmpty .resultProcessing}}
  result_processing = "{{quote .resultProcessing}}"
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

const taskWebServiceTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .summary}}
  summary = "{{quote .summary}}"
{{- end}}
{{- if notEmpty .url}}
  url = "{{quote .url}}"
{{- end}}
{{- if notEmpty .protocol}}
  protocol = "{{quote .protocol}}"
{{- end}}
{{- if notEmpty .httpMethod}}
  http_method = "{{quote .httpMethod}}"
{{- end}}
{{- if notEmpty .mimeType}}
  mime_type = "{{quote .mimeType}}"
{{- end}}
{{- if notEmpty .httpAuth}}
  http_auth = "{{quote .httpAuth}}"
{{- end}}
{{- if notEmpty .credentials}}
  credentials = "{{quote .credentials}}"
{{- end}}
{{- if notEmpty .payload}}
  payload = "{{quote .payload}}"
{{- end}}
{{- if notEmpty .responseProcessingType}}
  response_processing_type = "{{quote .responseProcessingType}}"
{{- end}}
{{- if notEmpty .statusCodeRange}}
  status_code_range = "{{quote .statusCodeRange}}"
{{- end}}
{{- if notEmpty .timeout}}
  timeout = {{.timeout}}
{{- end}}
{{- if isTrue .insecure}}
  insecure = true
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

const taskUniversalAWSS3Template = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .summary}}
  summary = "{{quote .summary}}"
{{- end}}
{{- if notEmpty .agent}}
  agent = "{{quote .agent}}"
{{- end}}
{{- if notEmpty .agentCluster}}
  agent_cluster = "{{quote .agentCluster}}"
{{- end}}
{{- if notEmpty .credentials}}
  credentials = "{{quote .credentials}}"
{{- end}}
  # Note: Universal task template fields may require manual adjustment
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

// ============================================================================
// Trigger Resources
// ============================================================================

const triggerTimeTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .description}}
  description = "{{quote .description}}"
{{- end}}
{{- if notEmpty .tasks}}
  tasks = [{{stringList .tasks}}]
{{- end}}
{{- if notEmpty .time}}
  time = "{{quote .time}}"
{{- end}}
{{- if notEmpty .timeZone}}
  time_zone = "{{quote .timeZone}}"
{{- end}}
{{- if notEmpty .timeStyle}}
  time_style = "{{quote .timeStyle}}"
{{- end}}
{{- if notEmpty .timeInterval}}
  time_interval = {{.timeInterval}}
{{- end}}
{{- if notEmpty .timeIntervalUnits}}
  time_interval_units = "{{quote .timeIntervalUnits}}"
{{- end}}
{{- if notEmpty .dayStyle}}
  day_style = "{{quote .dayStyle}}"
{{- end}}
{{- if notEmpty .calendar}}
  calendar = "{{quote .calendar}}"
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

const triggerCronTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .description}}
  description = "{{quote .description}}"
{{- end}}
{{- if notEmpty .tasks}}
  tasks = [{{stringList .tasks}}]
{{- end}}
{{- if notEmpty .minutes}}
  minutes = "{{quote .minutes}}"
{{- end}}
{{- if notEmpty .hours}}
  hours = "{{quote .hours}}"
{{- end}}
{{- if notEmpty .dayOfMonth}}
  day_of_month = "{{quote .dayOfMonth}}"
{{- end}}
{{- if notEmpty .month}}
  month = "{{quote .month}}"
{{- end}}
{{- if notEmpty .dayOfWeek}}
  day_of_week = "{{quote .dayOfWeek}}"
{{- end}}
{{- if notEmpty .dayLogic}}
  day_logic = "{{quote .dayLogic}}"
{{- end}}
{{- if notEmpty .timeZone}}
  time_zone = "{{quote .timeZone}}"
{{- end}}
{{- if notEmpty .calendar}}
  calendar = "{{quote .calendar}}"
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

const triggerFileMonitorTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .description}}
  description = "{{quote .description}}"
{{- end}}
{{- if notEmpty .tasks}}
  tasks = [{{stringList .tasks}}]
{{- end}}
{{- if notEmpty .taskMonitor}}
  task_monitor = "{{quote .taskMonitor}}"
{{- end}}
{{- if notEmpty .timeZone}}
  time_zone = "{{quote .timeZone}}"
{{- end}}
{{- if notEmpty .calendar}}
  calendar = "{{quote .calendar}}"
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

const triggerTaskMonitorTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  name = "{{quote .name}}"
{{- if notEmpty .description}}
  description = "{{quote .description}}"
{{- end}}
{{- if notEmpty .tasks}}
  tasks = [{{stringList .tasks}}]
{{- end}}
{{- if notEmpty .taskMonitor}}
  task_monitor = "{{quote .taskMonitor}}"
{{- end}}
{{- if notEmpty .timeZone}}
  time_zone = "{{quote .timeZone}}"
{{- end}}
{{- if notEmpty .calendar}}
  calendar = "{{quote .calendar}}"
{{- end}}
{{- if notEmpty .opswiseGroups}}
  opswise_groups = [{{stringList .opswiseGroups}}]
{{- end}}
}
`

// ============================================================================
// Workflow Components
// ============================================================================

const workflowVertexTemplate = `# Generated by sb2tf
resource "{{._terraformResource}}" "{{._resourceName}}" {
  workflow_name = "{{quote .workflowName}}"
  task_name     = "{{quote .taskName}}"
{{- if notEmpty .alias}}
  alias = "{{quote .alias}}"
{{- end}}
}
`

const workflowEdgeTemplate = `# Generated by sb2tf
# Edge: {{.sourceTask}} -> {{.targetTask}}
resource "{{._terraformResource}}" "{{._resourceName}}" {
  workflow_name = "{{quote .workflowName}}"
  source_id     = stonebranch_workflow_vertex.{{.sourceVertexTfName}}.vertex_id
  target_id     = stonebranch_workflow_vertex.{{.targetVertexTfName}}.vertex_id
}
`
