name: Feature Request
description: Suggest a new resource, data source, or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an improvement!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or changed?
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature be used? What problem does it solve?
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Proposed Configuration
      description: If applicable, show what the Terraform configuration might look like
      render: hcl
  - type: input
    id: api-endpoint
    attributes:
      label: StoneBranch API Endpoint
      description: If requesting a new resource, what API endpoint does it correspond to?
      placeholder: "/resources/..."
